/**
 * Hybrid Service Testing Script
 * Tests all 27 AI services with minimal token usage
 * Generates detailed report in logs/service-test-report.md
 */

import * as fs from 'fs';
import * as path from 'path';

// Service test results
interface TestResult {
  service: string;
  status: 'PASSED' | 'FAILED' | 'SKIPPED';
  error?: string;
  tokens?: { input: number; output: number };
  cost?: number;
  duration?: number;
  output?: any;
}

const results: TestResult[] = [];
let totalTokens = { input: 0, output: 0 };
let totalCost = 0;
const startTime = Date.now();

// Token cost per 1K tokens (AWS Bedrock Claude)
const COST_PER_1K_TOKENS = 0.003;

// Test logger
function log(message: string, type: 'info' | 'success' | 'error' | 'warn' = 'info') {
  const icons = { info: '📋', success: '✅', error: '❌', warn: '⚠️' };
  console.log(`${icons[type]} ${message}`);
}

// Calculate cost
function calculateCost(tokens: { input: number; output: number }): number {
  return ((tokens.input + tokens.output) / 1000) * COST_PER_1K_TOKENS;
}

// Test a service
async function testService(
  serviceName: string,
  testFn: () => Promise<any>
): Promise<void> {
  log(`\nTesting: ${serviceName}`, 'info');
  const serviceStartTime = Date.now();

  try {
    const result = await testFn();
    const duration = (Date.now() - serviceStartTime) / 1000;

    // Extract token usage if available
    const tokens = result?.usage || result?.tokens || { input: 0, output: 0 };
    const cost = calculateCost(tokens);

    totalTokens.input += tokens.input;
    totalTokens.output += tokens.output;
    totalCost += cost;

    results.push({
      service: serviceName,
      status: 'PASSED',
      tokens,
      cost,
      duration,
      output: result
    });

    log(`${serviceName} - PASSED`, 'success');
    log(`  Tokens: ${tokens.input + tokens.output} (in: ${tokens.input}, out: ${tokens.output})`);
    log(`  Cost: $${cost.toFixed(4)}`);
    log(`  Duration: ${duration.toFixed(2)}s`);
  } catch (error: any) {
    const duration = (Date.now() - serviceStartTime) / 1000;
    
    results.push({
      service: serviceName,
      status: 'FAILED',
      error: error.message,
      duration
    });

    log(`${serviceName} - FAILED`, 'error');
    log(`  Error: ${error.message}`, 'error');
  }
}

// Generate markdown report
function generateReport(): void {
  const duration = (Date.now() - startTime) / 1000;
  const passed = results.filter(r => r.status === 'PASSED').length;
  const failed = results.filter(r => r.status === 'FAILED').length;
  const skipped = results.filter(r => r.status === 'SKIPPED').length;

  let report = `# 🧪 Service Testing Report\n\n`;
  report += `**Date:** ${new Date().toLocaleString()}\n`;
  report += `**Duration:** ${Math.floor(duration / 60)}m ${Math.floor(duration % 60)}s\n\n`;

  report += `## 📊 Summary\n\n`;
  report += `| Metric | Value |\n`;
  report += `|--------|-------|\n`;
  report += `| Total Services | ${results.length} |\n`;
  report += `| ✅ Passed | ${passed} |\n`;
  report += `| ❌ Failed | ${failed} |\n`;
  report += `| ⏭️ Skipped | ${skipped} |\n`;
  report += `| 🎯 Success Rate | ${((passed / results.length) * 100).toFixed(1)}% |\n`;
  report += `| 📊 Total Tokens | ${totalTokens.input + totalTokens.output} |\n`;
  report += `| 💰 Total Cost | $${totalCost.toFixed(4)} |\n\n`;

  report += `## 📋 Service Results\n\n`;

  results.forEach(result => {
    const icon = result.status === 'PASSED' ? '✅' : result.status === 'FAILED' ? '❌' : '⏭️';
    report += `### ${icon} ${result.service}\n\n`;
    report += `- **Status:** ${result.status}\n`;
    
    if (result.status === 'PASSED') {
      report += `- **Tokens:** ${result.tokens!.input + result.tokens!.output} (in: ${result.tokens!.input}, out: ${result.tokens!.output})\n`;
      report += `- **Cost:** $${result.cost!.toFixed(4)}\n`;
      report += `- **Duration:** ${result.duration!.toFixed(2)}s\n`;
    } else if (result.status === 'FAILED') {
      report += `- **Error:** ${result.error}\n`;
      report += `- **Duration:** ${result.duration!.toFixed(2)}s\n`;
    }
    
    report += `\n`;
  });

  report += `---\n\n`;
  report += `**Generated by:** Hybrid Service Testing Script\n`;
  report += `**Test Mode:** Minimal token usage for cost efficiency\n`;

  // Ensure logs directory exists
  const logsDir = path.join(__dirname, '../logs');
  if (!fs.existsSync(logsDir)) {
    fs.mkdirSync(logsDir, { recursive: true });
  }

  // Write report
  const reportPath = path.join(logsDir, 'service-test-report.md');
  fs.writeFileSync(reportPath, report);
  
  log(`\n📄 Report generated: ${reportPath}`, 'success');
}

// Main test runner
async function runTests(): Promise<void> {
  log('🚀 Starting Hybrid Service Testing', 'info');
  log('Testing 27 AI services with minimal token usage\n', 'info');

  // Import services dynamically to avoid initialization errors
  try {
    // Test 1: Viral Analyzer
    await testService('viral-analyzer.service.ts', async () => {
      const { ViralAnalyzerService } = await import('./services/viral-analyzer.service');
      const service = new ViralAnalyzerService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 2: Content Multiplier V2
    await testService('content-multiplier-v2.service.ts', async () => {
      const { ContentMultiplierV2Service } = await import('./services/content-multiplier-v2.service');
      const service = new ContentMultiplierV2Service();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 3: Safety Service
    await testService('safety.service.ts', async () => {
      const { SafetyService } = await import('./services/safety.service');
      const service = new SafetyService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 4: Vernacular Service
    await testService('vernacular.service.ts', async () => {
      const { VernacularService } = await import('./services/vernacular.service');
      const service = new VernacularService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 5: Regional Network Service
    await testService('regional-network.service.ts', async () => {
      const { RegionalNetworkService } = await import('./services/regional-network.service');
      const service = new RegionalNetworkService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 6: Creative Director
    await testService('creative-director.service.ts', async () => {
      const { CreativeDirectorService } = await import('./services/creative-director.service');
      const service = new CreativeDirectorService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 7: ADHD Navigator
    await testService('adhd-navigator.service.ts', async () => {
      const { ADHDNavigatorService } = await import('./services/adhd-navigator.service');
      const service = new ADHDNavigatorService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 8: Platform Integration
    await testService('platform-integration.service.ts', async () => {
      const { PlatformIntegrationService } = await import('./services/platform-integration.service');
      const service = new PlatformIntegrationService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 9: Automation Service
    await testService('automation.service.ts', async () => {
      const { AutomationService } = await import('./services/automation.service');
      const service = new AutomationService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 10: Membership Service
    await testService('membership.service.ts', async () => {
      const { MembershipService } = await import('./services/membership.service');
      const service = new MembershipService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 11: Community Service
    await testService('community.service.ts', async () => {
      const { CommunityService } = await import('./services/community.service');
      const service = new CommunityService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 12: Knowledge Graph
    await testService('knowledge-graph.service.ts', async () => {
      const { KnowledgeGraphService } = await import('./services/knowledge-graph.service');
      const service = new KnowledgeGraphService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 13: Marketplace
    await testService('marketplace.service.ts', async () => {
      const { MarketplaceService } = await import('./services/marketplace.service');
      const service = new MarketplaceService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 14: Watermark
    await testService('watermark.service.ts', async () => {
      const { WatermarkService } = await import('./services/watermark.service');
      const service = new WatermarkService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 15: Dopamine Optimizer
    await testService('dopamine-optimizer.service.ts', async () => {
      const { DopamineOptimizerService } = await import('./services/dopamine-optimizer.service');
      const service = new DopamineOptimizerService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 16: Voice Clone
    await testService('voice-clone.service.ts', async () => {
      const { VoiceCloneService } = await import('./services/voice-clone.service');
      const service = new VoiceCloneService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 17: Trend Predictor
    await testService('trend-predictor.service.ts', async () => {
      const { TrendPredictorService } = await import('./services/trend-predictor.service');
      const service = new TrendPredictorService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 18: Workspace Service
    await testService('workspace.service.ts', async () => {
      const { WorkspaceService } = await import('./services/workspace.service');
      const service = new WorkspaceService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 19: Cultural Adapter
    await testService('cultural-adapter.service.ts', async () => {
      const { CulturalAdapterService } = await import('./services/cultural-adapter.service');
      const service = new CulturalAdapterService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 20: Viral Predictor
    await testService('viral-predictor.service.ts', async () => {
      const { ViralPredictorService } = await import('./services/viral-predictor.service');
      const service = new ViralPredictorService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 21: Ecosystem Analytics
    await testService('ecosystem-analytics.service.ts', async () => {
      const { EcosystemAnalyticsService } = await import('./services/ecosystem-analytics.service');
      const service = new EcosystemAnalyticsService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 22: Analytics Dashboard
    await testService('analytics-dashboard.service.ts', async () => {
      const { AnalyticsDashboardService } = await import('./services/analytics-dashboard.service');
      const service = new AnalyticsDashboardService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 23: Content DNA
    await testService('content-dna.service.ts', async () => {
      const { ContentDNAService } = await import('./services/content-dna.service');
      const service = new ContentDNAService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 24: Mode Detection
    await testService('mode-detection.service.ts', async () => {
      const { ModeDetectionService } = await import('./services/mode-detection.service');
      const service = new ModeDetectionService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 25: Quality Validator
    await testService('quality-validator.service.ts', async () => {
      const { QualityValidatorService } = await import('./services/quality-validator.service');
      const service = new QualityValidatorService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 26: AI Content Generator
    await testService('ai-content-generator.service.ts', async () => {
      const { AIContentGeneratorService } = await import('./services/ai-content-generator.service');
      const service = new AIContentGeneratorService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

    // Test 27: Platform Content Generator
    await testService('platform-content-generator.service.ts', async () => {
      const { PlatformContentGeneratorService } = await import('./services/platform-content-generator.service');
      const service = new PlatformContentGeneratorService();
      return { status: 'initialized', usage: { input: 0, output: 0 } };
    });

  } catch (error: any) {
    log(`Fatal error during testing: ${error.message}`, 'error');
  }

  // Generate report
  log('\n📊 Generating test report...', 'info');
  generateReport();

  // Summary
  const passed = results.filter(r => r.status === 'PASSED').length;
  const failed = results.filter(r => r.status === 'FAILED').length;
  
  log('\n' + '='.repeat(50), 'info');
  log('🎯 Testing Complete!', 'success');
  log(`✅ Passed: ${passed}/${results.length}`, 'success');
  log(`❌ Failed: ${failed}/${results.length}`, failed > 0 ? 'error' : 'info');
  log(`💰 Total Cost: $${totalCost.toFixed(4)}`, 'info');
  log(`📊 Total Tokens: ${totalTokens.input + totalTokens.output}`, 'info');
  log('='.repeat(50), 'info');
}

// Run tests
runTests().catch(error => {
  log(`Fatal error: ${error.message}`, 'error');
  process.exit(1);
});
